apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backbone
  template:
    metadata: 
      labels:
        app: backbone
    spec:
      serviceAccountName: microbackbone
      containers:
        - name: backbone
          image: 872859983801.dkr.ecr.ca-central-1.amazonaws.com/oag-backbone:1.0.1
          ports:
            - containerPort: 8080
              protocol: TCP